version: '3.4'

services:
  noderedisauthnoticateuser:
    image: noderedisauthnoticateuser
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 6700:6700
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
